# Generated by Django 3.0 on 2019-12-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['created_on']},
        ),
    ]
